### ISSUE TITLE
Chapter 2 Season 9 instead of Chapter 3 Season 1

### ISSUE THREAD

**Issue by McMistrzYT** [priyam-raj/timenite#1]
Please correct this mistake. It's now confirmed that chapter 3 is coming, with the "The End" event.

**Comment by McMistrzYT** [comment]
Also, the chapter is ending one day earlier, on December 4th.

**Comment by priyam-raj** [comment]
Hello, thanks for letting me know. Fixed all of it, could take a few minutes to reflect on the website.

**Comment by McMistrzYT** [comment]
Thanks!
